import Head from "next/head";
import Image from "next/image";
import { useTranslation } from "next-i18next";
import styles from "../styles/Home.module.css";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const { t } = useTranslation("common");
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>{t("hello")}</p>

      <button>
        <Link href={router.asPath} locale={"en"}>
          EN
        </Link>
      </button>

      <button>
        <Link href={router.asPath} locale={"es"}>
          ES
        </Link>
      </button>

      <main className={styles.main}></main>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  return {
    props: {
      ...(await serverSideTranslations(context.locale, ["common"])),
    },
  };
};
